<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="94" started-at="2017-10-28T17:05:50Z" finished-at="2017-10-28T17:05:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="94" started-at="2017-10-28T17:05:50Z" finished-at="2017-10-28T17:05:50Z">
      <class name="com.facebook.test.FbLoginTest">
        <test-method status="FAIL" signature="setupSuite()[pri:0, instance:com.facebook.test.FbLoginTest@1e397ed7]" name="setupSuite" is-config="true" duration-ms="70980" started-at="2017-10-28T22:34:39Z" finished-at="2017-10-28T22:35:50Z">
          <exception class="com.github.wasiqb.coteafs.appium.error.AppiumServerNotStartingError">
            <message>
              <![CDATA[Error occured while starting Appium server]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.github.wasiqb.coteafs.appium.error.AppiumServerNotStartingError: Error occured while starting Appium server
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.github.wasiqb.coteafs.error.util.ErrorUtil.fail(ErrorUtil.java:102)
	at com.github.wasiqb.coteafs.error.util.ErrorUtil.fail(ErrorUtil.java:70)
	at com.github.wasiqb.coteafs.appium.service.AppiumServer.start(AppiumServer.java:154)
	at com.facebook.test.FbLoginTest.setupSuite(FbLoginTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\DELL\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1, --log, F:\Eclipse_Oxygen\WorkSpace\fbTest\logs\server-1.log, --log-level, debug, --suppress-adb-kill-server, --backend-retries, 3, --local-timezone, --log-timestamp, --default-capabilities, {\"noReset\": \"false\", \"newCommandTimeout\": \"120\", \"fullReset\": \"false\"}] 

	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:149)
	at com.github.wasiqb.coteafs.appium.service.AppiumServer.start(AppiumServer.java:151)
	... 20 more
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/wd/hub/status] to be available after 60006 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:102)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:113)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:136)
	... 21 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:77)
	... 23 more
]]>
            </full-stacktrace>
          </exception> <!-- com.github.wasiqb.coteafs.appium.error.AppiumServerNotStartingError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method status="SKIP" signature="test1()[pri:0, instance:com.facebook.test.FbLoginTest@1e397ed7]" name="test1" duration-ms="0" started-at="2017-10-28T22:35:50Z" finished-at="2017-10-28T22:35:50Z">
          <exception class="com.github.wasiqb.coteafs.appium.error.AppiumServerNotStartingError">
            <message>
              <![CDATA[Error occured while starting Appium server]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.github.wasiqb.coteafs.appium.error.AppiumServerNotStartingError: Error occured while starting Appium server
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.github.wasiqb.coteafs.error.util.ErrorUtil.fail(ErrorUtil.java:102)
	at com.github.wasiqb.coteafs.error.util.ErrorUtil.fail(ErrorUtil.java:70)
	at com.github.wasiqb.coteafs.appium.service.AppiumServer.start(AppiumServer.java:154)
	at com.facebook.test.FbLoginTest.setupSuite(FbLoginTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\DELL\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1, --log, F:\Eclipse_Oxygen\WorkSpace\fbTest\logs\server-1.log, --log-level, debug, --suppress-adb-kill-server, --backend-retries, 3, --local-timezone, --log-timestamp, --default-capabilities, {\"noReset\": \"false\", \"newCommandTimeout\": \"120\", \"fullReset\": \"false\"}] 

	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:149)
	at com.github.wasiqb.coteafs.appium.service.AppiumServer.start(AppiumServer.java:151)
	... 20 more
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/wd/hub/status] to be available after 60006 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:102)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:113)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:136)
	... 21 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:77)
	... 23 more
]]>
            </full-stacktrace>
          </exception> <!-- com.github.wasiqb.coteafs.appium.error.AppiumServerNotStartingError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="teardownTestSuite()[pri:0, instance:com.facebook.test.FbLoginTest@1e397ed7]" name="teardownTestSuite" is-config="true" duration-ms="0" started-at="2017-10-28T22:35:50Z" finished-at="2017-10-28T22:35:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownTestSuite -->
      </class> <!-- com.facebook.test.FbLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
